apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: app-4-dev
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: angular-app-4
  template:
    metadata:
      labels:
        app: angular-app-4
    spec:
      containers:
        - name: angular-app-4
          image: dokkaushik/angular-app-4:042a2ddc5d93b80fd8bb4b8ffee8405d6a2eed0c
          ports:
            - containerPort: 80
